### core concept
标准流程:try-throw-catch
```C++
try {

}
catch(...){

}
```
### 问题
1. 貌似不能再try外面thow异常